spring.application.name=realtime-messaging-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/realtime_chat_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:8359}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=

server.port=${PORT:8080}